[workspace]

members = [
    "comms",
    "comms_derive",
    "terminal",
    "wam",
]


[workspace.dependencies]
defmt = "0.3.2"
log = "0.4.17"
minicbor = { version = "0.19.0", features = ["derive"] }
