[package]
name = "wam"
version = "0.1.0"
authors = ["samuel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "0.2.7"
log = { version = "0.4.17", optional = true }
nb = "1.0.0"
num_enum = { version = "0.5.7", default-features = false }
sha2 = { version = "0.10.6", default-features = false }

[features]
logging = [ "dep:log", "std" ]
std = []
